bcgov/nr-spar

- .github/workflows/ci.yml
---
[Backend](https://nr-spar-21-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-21-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-21-oracle-api.apps.silver.devops.gov.bc.ca/)
> Added Trivy to ci.yml

- .github/workflows/pr-close.yml
- .github/workflows/pr-open.yml
Handle PR open and close concurrency so that they can interrupt each other.  This prevents orphaning OpenShift artifacts and skips more quickly to the most recent workflow.
---
[Backend](https://nr-spar-58-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-58-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-58-oracle-api.apps.silver.devops.gov.bc.ca/)
> PR open and close concurrency

- .github/workflows/merge-main.yml
- .github/workflows/pr-open.yml
- frontend/CONTRIBUTING.md
- frontend/README.md
- frontend/jest.config.js
- frontend/openshift.deploy.yml
Fixes wrong Back-end api URLs addresses.
This was tested locally, and will be tested with new depoyments.
---
[Backend](https://nr-spar-76-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-76-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-76-oracle-api.apps.silver.devops.gov.bc.ca/)
> fix: wrong backend api urls

- .github/workflows/pr-open.yml
- backend/openshift.deploy.yml
- common/openshift.init.yml
- oracle-api/openshift.deploy.yml
Fix vars/secrets that have been loaded with manual secrets.
---
[Backend](https://nr-spar-74-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-74-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-74-oracle-api.apps.silver.devops.gov.bc.ca/)
> Stop using manual secrets, plus secret and variable cleanup

- backend/Dockerfile
a simple PR to update eclipse-temurin used in `/backend/Dockerfile`, the old one gives me RPC error on my macbook
---
[Backend](https://nr-spar-89-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-89-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-89-oracle-api.apps.silver.devops.gov.bc.ca/)
> feat: upgrade eclipse-temuri so it works with apple chips

- backend/Dockerfile
- database/Dockerfile
- docker-compose.yml
- frontend/Dockerfile
- frontend/Dockerfile.dev
- oracle-api/Dockerfile
Consolidate Docker Compose and Dockerfile Healthchecks into just Dockerfiles.
Small adjustment to keep ./node_modules local.
---
[Backend](https://nr-spar-147-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-147-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-147-oracle-api.apps.silver.devops.gov.bc.ca/)
> Docker Compose adjustments

- .github/workflows/pr-open.yml
GitHub hasn't been performing wonderfully.  Our PR description adder can double up messages if the call to GitHub times out.  This change lets the commenter run on opened or reopened PRs.  It also prevents using a GitHub runner, which is handy when they're in short supply and we end up queued.
---
[Backend](https://nr-spar-171-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-171-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-171-oracle-api.apps.silver.devops.gov.bc.ca/)
> Run PR description add if PR opened or reopened

- .github/workflows/pr-open.yml
- backend/openshift.deploy.yml
- frontend/openshift.deploy.yml
- oracle-api/openshift.deploy.yml
Add autoscaling to oracle api, configured the same way as backend service
DEV: Min=1, Max=1
TEST & PROD: Min=3, MAX=5
---
[Backend](https://nr-spar-170-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-170-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-170-oracle-api.apps.silver.devops.gov.bc.ca/)
> fix: add autoscaling to oracle api

- .github/workflows/pr-open.yml
- backend/Dockerfile
- backend/pom.xml
Cloud Native standalone builds break the QuickStart workflow.  We can either add support for that to the builder or stuff Cloud Native into a Dockerfile.  This PR tries the latter.
---
[Backend](https://nr-spar-163-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-163-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-163-oracle-api.apps.silver.devops.gov.bc.ca/)
> Backend Cloud Native in Dockerfile

- frontend/openshift.deploy.yml
Frontend is timing out.  This increases the probes' failure thesholds.
---
[Backend](https://nr-spar-191-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-191-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-191-oracle-api.apps.silver.devops.gov.bc.ca/)
> bug: increase probe failure thresholds

- oracle-api/openshift.deploy.yml
The oracle-api service is down on both test and prod, this hotfix is aimed to reduce the number of pods thus decreasing the amount of connection to the oracle DB, Ricardo mentioned the maximum is 5. 
The new config has min of 1 and max of 2 pods for oracle-api
---
[Backend](https://nr-spar-219-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-219-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-219-oracle-api.apps.silver.devops.gov.bc.ca/)
> hotfix: reduce replicas for auto scaler

- .github/workflows/pr-open.yml
Deployment triggers are used to conditionally deploy components.  This speeds up PR deployments by picking required components using triggers.
---
[Backend](https://nr-spar-255-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-255-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-255-oracle-api.apps.silver.devops.gov.bc.ca/)
> feat: PR deployment triggers

- backend/src/main/java/ca/bc/gov/backendstartapi/repository/FavouriteActivityRepository.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/FavouriteActivityService.java
Update `backend` to keep only one highlighted favourite activity to an user.
Fixes #241 
This was tested locally.
---
[Backend](https://nr-spar-250-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-250-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-250-oracle-api.apps.silver.devops.gov.bc.ca/)
> feat: keep only one highlighted activity to user

- .github/workflows/pr-open.yml
- common/trigger.txt
I introduced deploy triggers with commas that shouldn't have been there.  This action removes them.  Please expect a few commits to be made/removed during testing.
Thanks to @RMCampos for catching this and troubleshooting.  :)
---
[Backend](https://nr-spar-296-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-296-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-296-oracle-api.apps.silver.devops.gov.bc.ca/)
> bug: commas on deploy action triggers

- .github/CODEOWNERS
Remove DerekRoberts (me!) and SLDonnelly (Sabina) from .github/codeowners, since we're no longer necessary.  Good job team.  :)
We'll still have admin rights on the repo and can help out as necessary.
---
[Backend](https://nr-spar-344-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-344-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-344-oracle-api.apps.silver.devops.gov.bc.ca/)
> Cut down .github/codeowners

- frontend/src/api-service/filesAndDocsAPI.ts
- frontend/src/api-service/recentActivitiesAPI.ts
- frontend/src/components/RecentActivities/RecentActivitiesTable/index.tsx
- frontend/src/components/RecentActivities/index.tsx
- frontend/src/mock-server/fixtures/FilesDocsItems.ts
this fixes an issue where the mock server is not operating correctly, it crashes local, test, and dev environment. 
this is related to the task where changes were made to recent activities. 
The exact reason on why this error wasn't happening during code review needs to be investigated.
Basically mock server does not run on test and prod, but it should run on dev. 
Instead of returning an array of file docs, it returns `{}` thus causing the `elements.map()` is not a function error.
---
[Backend](https://nr-spar-346-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-346-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-346-oracle-api.apps.silver.devops.gov.bc.ca/) …
> hotfix: replaced mock server call with dummy data

- .github/CODEOWNERS
I dun goof't by removing Sabina from codeowners.  This is a correction.
---
[Backend](https://nr-spar-345-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-345-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-345-oracle-api.apps.silver.devops.gov.bc.ca/)
> chore: restore SLDonnelly in .github/codeowners

- .github/workflows/merge-main.yml
- .github/workflows/pr-open.yml
- backend/openshift.fluentbit.yml
FluentBit is consuming a namespace variable to add into metadata.  This is generally unnecessary, but not always.  For now I'm removing the variable.  If that fails we can use a GitHub Environment to handle DEV/TEST/PROD differences.
---
[Backend](https://nr-spar-431-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-431-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-431-oracle-api.apps.silver.devops.gov.bc.ca/)
> bug: clip namespace from fluentbit metadata

- backend/openshift.deploy.yml
- backend/src/main/resources/application.properties
- docker-compose.yml
- oracle-api/Dockerfile
Caddy in docker-compose.yml.
Run caddy (serves frontend), backend and database:
`docker compose up caddy`
Run caddy and oracle-api:
`docker compose up caddy oracle-api`
Extra: Backend vars changed to line up with expected Postgres vars.  Good for consistency, but not a deal breaker.
---
[Backend](https://nr-spar-443-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-443-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-443-oracle-api.apps.silver.devops.gov.bc.ca/)
> feat: caddy in compose and var consistency

- frontend/src/components/InfoSection/InfoSectionColumn/index.tsx
A tooltip was displayed when a user hovered over an input at the bottom of the page in Step 5. This behavior has been removed. To do this I had to remove the placeholder, as there is no easy way to remove the tooltip from the carbon components.
Fixes #[#387](https://github.com/bcgov/nr-spar/issues/387)
---
[Backend](https://nr-spar-491-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-491-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-491-oracle-api.apps.silver.devops.gov.bc.ca/)
[Main Merge …
> fix: remove tooltip on step 5

- frontend/Caddyfile
Allow IBM CDN to serve font files
Related to #490 
---
[Backend](https://nr-spar-517-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-517-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-517-oracle-api.apps.silver.devops.gov.bc.ca/)
> fix: allow ibm cdn

- frontend/Caddyfile
Closes #673 
- Added AWS Cognito Identity Provider address to allowed connect-src on Caddy.
- Caddy file
- None
Tested locally with docker compose test version.
No gif again, sorry. I guess Encora could be blocking it here, I see no gifs at all, only  that github icon loading :(
---
[Backend](https://nr-spar-684-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-684-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-684-oracle-api.apps.silver.devops.gov.bc.ca/)
> fix: add cognito idp to connect-src policy

- docker-compose.yml
Simply get `oracle-api` service url `test` back. This change was first addresed when testing FAM so we needed everything running locally, but now we can get it back
- None
- Docker compose file environment values pointing back to `test` Oracle REST service instead of local.
- None
I'll get a gif as soon as I make this extension work =D
---
[Backend](https://nr-spar-683-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-683-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-683-oracle-api.apps.silver.devops.gov.bc.ca/)
[Main Merge …
> fix: get oracle test url back on docker compose file

- .github/workflows/pr-open.yml
- docker-compose.yml
Closes #201 
- None.
- The `docker-compose.yml` file.
- None.
⚠️ Note that the change was made only for `backend`, no need to do it for Oracle. Since having it enable for one of them should be enough.
---
[Frontend](https://nr-spar-46-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-46-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-46-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
Any successful deployments (not always required) will be available …
> fix: enable backend rest api to report apache maven plugins validations

- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
- frontend/src/types/ParentTreeGeneticQualityType.ts
Closes #842 
- Empty section that informs users the orchard is empty
- The logic that process parent tree data
- None
---
[Frontend](https://nr-spar-43-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-43-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-43-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> Fix/842 Empty orchard bug

- backend/src/main/java/ca/bc/gov/backendstartapi/config/NativeImageConfig.java
- backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedPlanZoneDto.java
- backend/src/main/java/ca/bc/gov/backendstartapi/entity/SeedlotSeedPlanZoneEntity.java
- backend/src/main/java/ca/bc/gov/backendstartapi/provider/OracleApiProvider.java
- backend/src/main/java/ca/bc/gov/backendstartapi/provider/Provider.java
- backend/src/main/java/ca/bc/gov/backendstartapi/repository/SeedlotSeedPlanZoneEntityRepository.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotOrchardService.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotFormPutTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotServiceTest.java
Closes #794 
- Methods for fetching SPZ information from Oracle;
- Oracle provider class
- SeedlotService when saving the form
- None;
---
[Frontend](https://nr-spar-11-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-11-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-11-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: update seedlot with spz information

- common/openshift.fluentbit.yml
I'm getting slammed with emails complaining about PVC capacity for fluentbit.  This dials it up from 50 to 75 Mi in a desperate bit for some peace.
---
[Frontend](https://nr-spar-33-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-33-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-33-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): loads of pvc capacity emails about fluentbit

- .github/workflows/pr-open.yml
- database/openshift.deploy.yml
Nag messages from OCIO are complaining about PVC being near capacity.  We should haven't to adjust, but we do.  Here's the adjustment.
---
[Frontend](https://nr-spar-46-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-46-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-46-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): bump PR db PVC size to silence nag emails

- .github/workflows/merge.yml
- .github/workflows/scheduled.yml
Cypress currently needs work to pass outside of PRs.  That'll be handled in a later PR.
---
- [Frontend](https://nr-spar--frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1011-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1011-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): disable cypress outside of PRs

- .github/workflows/.deploy.yml
- .github/workflows/pr-open.yml
Since we may or may not (currently the case for TEST) want to run Cypress tests, they are now controlled with the deployer and `test: true|false`.
---
- [Frontend](https://nr-spar-9-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1059-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1059-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): roll tests into .deploy.yml

- .github/pull_request_template.md
- README.md
Replacing `#(issue)` with `#issue` in the PR template lets GitHub run a live lookup of PR number by description!
Bonus: Revised badges in README.md.
- goodbye visually appealing, but functionality crippling brackets!
---
- [Backend](https://nr-spar-1070-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1070-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/ …
> fix(ci): drop brackets from PR template for dynamic lookup

- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
I hate demo environments!  How could you do this to me?!?  Closes #982.
Ideally we won't need a demo environment and can instead point PRs to PRs to PRs until the world is right again.  That could become an issue if PRs become too large, but at least the visibility and paper trails are good.
- Add workflow_dispatch to main.yml
- Deploy any tag directly to TEST and then PROD
- OR deploy to DEMO only
- Add support for demo environment
- deploy with new dispatch
- OR push to branch=demo
- Steps to run workflow:
- Visit Actions > All Workflows > Merge ((here)[https://github.com/bcgov/nr-spar/actions/workflows/merge.yml])
- Click "Run workflow"
- Use wizard/pull-down to launch
---
- …
> feat(ci): add workflow_dispatch and ref=demo to merge.yml

- backend/src/main/resources/db/migration/V33__ETL_tool_monitoring_tables_update.sql
- sync/openshift.deploy.yml
Include changes in the monitoring/config tables for ETL Tool.
Closes #1041
-
-
-
---
- [Frontend](https://nr-spar-28-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1128-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1128-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: Including ETL_TABLE changes and first processes to be executed

- .github/workflows/.deploy.yml
- sync/openshift.deploy.yml
Prevents ETL job collisions on workflow retries.  Speeds up ETL with test mode.
- Appended github.run_attempt to job names
- Dropped ETL runs to just test mode - this can be revisited, likely while optimizing
---
- [Frontend](https://nr-spar-1-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1151-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1151-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml …
> fix(ci): add run attempt to job runs, avoiding retry collisions

- .github/workflows/.deploy.yml
- re-enabled ETL true|false check in .deploy
- stop ETL from running in main merge workflow
---
- [Frontend](https://nr-spar-13-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1163-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1163-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): disable ETL

- .github/workflows/pr-open.yml
- backend/openshift.deploy.yml
- database/openshift.deploy.yml
- frontend/openshift.deploy.yml
- oracle-api/openshift.deploy.yml
Closes #1169 
- workflows now pick up images directly from ghcr.io
- removed image streams, which are sort of OpenShift's container registry
---
- [Backend](https://nr-spar-1170-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1170-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): drop image streams

- .github/workflows/pr-open.yml
- backend/openshift.deploy.yml
- common/openshift.fluentbit.yml
- database/openshift.deploy.yml
- frontend/openshift.deploy.yml
- oracle-api/openshift.deploy.yml
DeploymentConfigs (OpenShift) have been deprecated in favour of deployments (Kubernetes).
- Deployment objects for OpenShift templates
- DeploymentConfig objects in OpenShift templates
---
- [Frontend](https://nr-spar-22-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1172-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1172-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): replace deploymentconfigs with deployments

- backend/src/main/java/ca/bc/gov/backendstartapi/config/NativeImageConfig.java
add reflection config for area of use dtos for native image
---
- [Backend](https://nr-spar-1182-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1182-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: add area of use reflections

- backend/src/main/java/ca/bc/gov/backendstartapi/config/NativeImageConfig.java
- backend/src/main/java/ca/bc/gov/backendstartapi/dto/oracle/AreaOfUseDto.java
- oracle-api/src/main/java/ca/bc/gov/backendstartapi/dto/AreaOfUseDto.java
add constructors
---
- [Backend](https://nr-spar-1183-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1183-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: area of use dto constructors

- frontend/src/api-service/applicantAgenciesAPI.ts
- frontend/src/api-service/fixtures/MockForestClients.ts
- frontend/src/api-service/forestClientsAPI.ts
Forest client is down without a definite time to be up again. 
Mocking the FC api return values on the front-end to unblock dev works. 
The TODO comments is there for use to easily find the code that needs to be restored once FC is up. 
I thought about having an env var on the front-end similar to back-end that can mock return data on the fly, but i don't think it's necessary. 
You might see something like this but it's expected and can be ignored, the purpose of this small PR is to enable devs to gain access to all the pages.
---
- [Frontend](https://nr-spar-40-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1190-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- …
> fix: mock forest client front end

- .github/workflows/.deploy.yml
- .github/workflows/pr-open.yml
Handles false passes in pr-open.yml.  This had led to breaks in other PRs and TEST.
- Extra checks and output for PR Results job
---
- [Backend](https://nr-spar-1247-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1247-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): explicitly scrub needs for failures

- backend/pom.xml
- database/Dockerfile
- docker-compose.yml
Fixes a break where Postgres 15.7 is rejected by Flyway.
- Dialed down deployment Postgis from 15 to 14
- Dialed up Compose Postgis from 13 to 14
---
- [Backend](https://nr-spar-1249-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1249-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat(ci): Postgis and Flyway

- .github/workflows/.tests.yml
- frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-collection-interim.cy.ts
- frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
- frontend/cypress/e2e/smoke-test/my-seedlots.cy.ts
- frontend/cypress/e2e/smoke-test/seedlot-dashboard.cy.ts
- frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
- frontend/src/components/SeedlotRegistrationSteps/CollectionStep/styles.scss
- frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/SingleOwnerInfo/index.tsx
- frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/SingleOwnerInfo/styles.scss
- frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/utils.ts
Closes N/A
Our cypress have been failing silently, this PR is to address the issue.
- Cypress should fail if a test fails
- Fixed a problem where clearing a number input will make it default to '0', then typing '02' will sometimes making it '020' thus affecting the values to be tested. This is nearly impossible to happen with human input but it happens with Cypress. 
- Renamed some tests so it's more straight to the point
- Restructured the test that checks funding source and method of payment
- Improved the save checking logic
---
- [Frontend](https://nr-spar-0-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1250-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- …
> fix: cypress tests and number inputs

- backend/pom.xml
Closes #1231 
- None;
- pom.xml file.
- Java dependency;
---
- [Frontend](https://nr-spar-1-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1251-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1251-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: remove MS XML-based files support

- renovate.json
- Excluded frontend's vite-plugin-istanbul v6.0.0 from Renovate
---
- [Frontend](https://nr-spar-10-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1260-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1260-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): Renovate exclude vite-plugin-istanbul

- backend/openshift.deploy.yml
- oracle-api/openshift.deploy.yml
- Adds new SPAR URL to allowed origins on both Postgres and Oracle backend API;
- None;
- openshift deployment files for Postgres and Oracle;
- None;
---
- [Backend](https://nr-spar-1264-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1264-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: enable new spar urls

- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotFormPutTest.java
- frontend/src/api-service/seedPlanUnitAPI.ts
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/utils.ts
- frontend/src/components/SeedlotReviewSteps/AreaOfUse/utils.ts
- frontend/src/components/SeedlotReviewSteps/Collection/GeoInfo.tsx
- frontend/src/components/SeedlotReviewSteps/Collection/Read/index.tsx
- frontend/src/components/SeedlotReviewSteps/Collection/constants.ts
- frontend/src/components/SeedlotReviewSteps/Collection/utils.ts
- frontend/src/utils/NumberUtils.ts
- frontend/src/views/Seedlot/ContextContainerClassA/context.tsx
- frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
- frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
- frontend/src/views/Seedlot/SeedlotReview/constants.ts
- frontend/src/views/Seedlot/SeedlotReview/definitions.ts
- oracle-api/src/main/java/ca/bc/gov/backendstartapi/service/SeedPlanUnitService.java
Closes #1211
Note that the app's UI is outdated, so it won't look the same as Figma, we'll need to have another task for it
BEC Zone and SPU data are read only
- Display BEC Values, Collection Geo data
- Validate Inputs
- [backend] Fill in seed_plan_unit upon submitting a seedlot form 
- None
---
- [Frontend](https://nr-spar-39-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1289-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1289-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
After merge, new images are …
> feat: 1211 display and edit bec values

- frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
- frontend/src/views/Seedlot/SeedlotDetails/index.tsx
Enable seedlot review button on seedlots with status other than PND or INC, previously only seedlots with submitted status have that button enabled.
Also fixed a problem where null value will trigger .toString() errors
---
- [Frontend](https://nr-spar-42-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1292-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1292-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …
> fix: enable seedlot review button

- backend/src/main/java/ca/bc/gov/backendstartapi/config/ImageTagVersionConfig.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/config/ImageTagVersionConfig.java
- Image Tag version configs on both Postgres and Oracle;
- None;
- None;
---
- [Backend](https://nr-spar-1319-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1319-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: show image tag version on actuator health page

- .github/workflows/.deploy.yml
Required to fix PROD deployments of oracle-api.  Handle ORACLE_SERVICE (or SERVICE_NAME) with GitHub Secrets instead of juggling the config in .deploy.yml.
- vars.ORACLE_SERVICE for repo
- vars.ORACLE_SERVICE override for prod
- SERVICE_NAME and logic removed from .deploy.yml
---
- [Frontend](https://nr-spar-22-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1322-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1322-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- …
> fix(ci): handle ORACLE_SERVICE with GH secrets

- .github/workflows/.deploy.yml
- .github/workflows/merge.yml
- backend/openshift.deploy.yml
- backend/src/main/resources/application.properties
- common/openshift.fluentbit.yml
- common/openshift.init.yml
- oracle-api/openshift.deploy.yml
- oracle-api/src/main/resources/application.properties
- Only run FluentBit when `fluentbit_target` is provided
- Only provide `fluentbit_target` for TEST and PROD
- Move fluentbit config from init into fluentbit deploy
- Drop fluentbit secret object, pass into deployment
---
- [Frontend](https://nr-spar-30-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1330-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1330-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …
> chore(ci): Run FluentBit in TEST and PROD only

- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/definitions.ts
Closes #1252
Removed unused columns on the table as described in the issue
---
- [Backend](https://nr-spar-1334-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1334-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: remove mean geospatial columns

- frontend/src/api-service/orchardAPI.ts
- frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
- frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
- oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/OrchardRepository.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/ParentTreeRepository.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/service/OrchardService.java
- oracle-api/src/test/java/ca/bc/gov/oracleapi/repository/OrchardRepositoryTest.java
- oracle-api/src/test/java/ca/bc/gov/oracleapi/service/OrchardServiceTest.java
The purpose of this PR is to allow data with retired orchard and parent trees under retired orchard to appear correctly   
- allow Oracle orchard endpoint to return all stages of Orchards by removing the filter for retired orchards
- filter retired orchards on orchard step of the reg form instead
- return all parent trees under a veg code regardless of orchard's stage code
---
- [Frontend](https://nr-spar-46-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1346-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1346-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Analysis …
> fix: return all stages of orchards

- .github/workflows/.deploy.yml
- common/openshift.init.yml
- docker-compose.yml
- sync/src/main.py
Splits out envars for sync.
- Vars/secrets for ORACLE_SYNC_USER and ORACLE_SYNC_PASSWORD
-  Values changed for pick up
---
- [Frontend](https://nr-spar-12-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1362-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1362-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): split out sync envars

- frontend/src/views/Seedlot/SeedlotDetails/index.tsx
- frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
- frontend/src/views/Seedlot/SeedlotReview/index.tsx
- only tsc admin can see the review button
- only seedlot status in 'SUB' can be send back to pending or approved
---
- [Frontend](https://nr-spar-13-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1363-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1363-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: better seedlot review rbac

- docker-compose.yml
- sync/config/SQL/SPAR/POSTGRES_SEEDLOT_PARENT_TREE_EXTRACT.sql
Address issue: ORA-01400: cannot insert NULL into ("THE"."SEEDLOT_PARENT_TREE"."TOTAL_GENETIC_WORTH_CONTRIB")
-
-mod POSTGRES_SEEDLOT_PARENT_TREE_EXTRACT.sql to default to 0
-
---
- [Backend](https://nr-spar-1369-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1369-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: addressnulls

- backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
- backend/src/main/java/ca/bc/gov/backendstartapi/security/LoggedUserService.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
- backend/src/test/java/ca/bc/gov/backendstartapi/security/LoggedUserServiceTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotServiceTest.java
- frontend/src/components/SeedlotCards/constants.ts
- frontend/src/components/SeedlotCards/index.tsx
- frontend/src/contexts/AuthProvider.tsx
Closes #1375
- AuthContext method to get when a user is admin
- Seedlot service to allow admin to get seedlots by number
---
- [Backend](https://nr-spar-1381-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1381-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: network error upon login for tsc admin profile

- sync/src/module/database_connection.py
Bug fix for issue getting rowcount when no soq data exists
-
-
-
---
- [Backend](https://nr-spar-1384-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1384-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: return of rowcount

- backend/openshift.deploy.yml
- backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
- backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/TscAdminEndpoint.java
- backend/src/main/java/ca/bc/gov/backendstartapi/security/LoggedUserService.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
- backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpointTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/TscAdminEndpointTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotFormPutTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotServiceTest.java
- Fix the form submission when it's subbmited by someone with Admin powers.
- Seedlot service;
- Maximum memory for the backend;
---
- [Frontend](https://nr-spar-39-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1389-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1389-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: enable the tsc admin to submit the form as a regular user

- docker-compose.yml
- oracle-api/openshift.deploy.yml
- oracle-api/src/main/java/ca/bc/gov/oracleapi/dto/SparBecZoneDescriptionDto.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/SparBecCatalogueRepository.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/service/OrchardService.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/service/SparBecCatalogueService.java
- oracle-api/src/test/java/ca/bc/gov/oracleapi/service/OrchardServiceTest.java
- oracle-api/src/test/java/ca/bc/gov/oracleapi/service/SparBecCatalogueServiceTest.java
Closes #1393 
- SPAR Bec Zones Service to get all codes at once.
---
- [Frontend](https://nr-spar-45-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1395-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1395-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: orchard requests taking too long

- backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
- backend/src/main/java/ca/bc/gov/backendstartapi/provider/OracleApiProvider.java
- backend/src/main/java/ca/bc/gov/backendstartapi/provider/Provider.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/OrchardService.java
- backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpointTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/provider/OracleApiProviderTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/OrchardServiceTest.java
- frontend/src/api-service/ApiConfig.ts
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/UnrelatedGenWorth.tsx
Closes #1396 
- Postgres API removing proxy request. (no reason to have that in the first place)
- Orchard API request from Postgres.
---
- [Frontend](https://nr-spar-48-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1398-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1398-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: remove postgress from orchard vegcodes request

- .github/workflows/.deploy.yml
- .github/workflows/.tests.yml
- .github/workflows/pr-open.yml
- frontend/Dockerfile
Deployment triggers haven't been working as intended.  There's a race condition where if an omitted/skipped build runs last, previous build triggers are ignored.
Also, there were significant changes made to the deployer to accommodate the frequent validation failures for backend and oracle-api. 
- Improved support for watching deployments
- Triggers and logic added to .deploy.yml
- Lots of logic, but little is genuinely different
- Build outputs and deployment triggers removed from pr-open.yml
---
- [Frontend](https://nr-spar-6-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1406-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1406-oracle-api.apps.silver.devo …
> chore(ci): improve deploy triggers and longer-running validations

- .github/workflows/sync-job.yml
Closes #1137 .  This is the bug-squashing follow-up to #1408.  The job had to be renamed to avoid colons (`:`).
---
- [Frontend](https://nr-spar-9-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1409-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1409-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): schduled job illegal characters

- .github/workflows/sync-job.yml
Follows the progress of the ETL sync job.  Test added to ensure success.
---
- [Frontend](https://nr-spar-12-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1412-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1412-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat(ci): follow progress of ETL job

- .github/workflows/cypress-nightly.yml
The Cypress Nightly job has been failing and was disabled.  This PR points it to the same shared workflows as pr-open.yml, but using test as the target.
- Reenabled Cypress Nightly
- Pointed to shared workflows (.tests.yml)
---
- [Backend](https://nr-spar-1414-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1414-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …
> fix(ci): cypress nightly

- .github/workflows/sync-job.yml
The ETL job requires a specific version of oc.  Using curl doesn't consistently work, so this swaps to wget, adds contiuing partial downloads, a retry and continuing on error (w/ GitHub default oc).
- Resume downloads
- Retry
- Continue on error
- Swapped curl for wget
---
- [Backend](https://nr-spar-1419-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1419-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …
> feat(ci): make oc update more resilient

- .github/workflows/pr-close.yml
- .github/workflows/pr-validate.yml
Tries to address duplicate PR messages by updating quickstart helpers version, which has an attempted fix.
---
- [Frontend](https://nr-spar-28-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1428-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1428-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(deps): bump quickstart helpers version

- .github/workflows/job-nightly.yml
- README.md
Still working on failures in the Nightly (formerly Scheduled) job.  OpenShift cleanup is being limited to just deployments, which still cleans up pods.  Cleanup window shortened from 7 to 4 days.
- Now only deleting deployments and their dependents (e.g. pods, replica controllers, horizondal pod autoscalers)
- Shorted cleanup windows from 7 to 4 days
---
- [Frontend](https://nr-spar-30-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1430-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1430-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Analysis …
> fix(ci): scheduled cleanup deployements only, keep 4 days

- .github/workflows/analysis.yml
- .github/workflows/job-nightly.yml
- Switched to GitHub's new default CodeQL setup
- Our code, which is no longer required!
---
- [Backend](https://nr-spar-1431-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1431-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): switch to GH default CodeQL

- .github/workflows/analysis.yml
- README.md
Removed Analysis badge, since it can be triggered by PRs or main merge.  Only the latter would be useful.
---
- [Backend](https://nr-spar-1432-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1432-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> docs: remove Analysis badge, overly noisy (PR)

- .github/workflows/demo.yml
Keep working on workflow triggers.
---
- [Frontend](https://nr-spar-45-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1445-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1445-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): revise DEMO URL triggers

- .github/workflows/job-sync.yml
- sync/openshift.deploy.yml
We can't fire up OpenShift jobs without a cronjob, so a schedule is required.  This PR sets the schedule to once every 1000 years, which would be infrequent enough to be ignorable.
- Cronjob schedule is now: `0 0 1 1/12000 *`
- "00:00 on day-of-month 1 in every 12000th month from January through December`
---
- [Frontend](https://nr-spar-0-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1450-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1450-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
After merge, …
> chore(ci): sync job conversion

- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotGeneticWorthService.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotFormPutTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotGeneticWorthServiceTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotServiceTest.java
Closes #1426 
- Seedlot Genetic Worth table being saved twice.
---
- [Backend](https://nr-spar-1433-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1433-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
- [Frontend](https://nr-spar-33-frontend.apps.silver.devops.gov …
> fix: disable seedlot gen worth saving at the wrong place and time

- .github/workflows/release.yml
Closes #1441 
It'll take a few iterations, but the idea is to deploy to PROD when new releases are published or updated.
- Release workflow
---
- [Frontend](https://nr-spar-16-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1466-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1466-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat(ci): deploy on release

- common/openshift.init.yml
- oracle-api/openshift.deploy.yml
- sync/openshift.deploy.yml
Sync didn't have its own secrets object, which would have been fine, except it differs from oracle-api enough to create confusion.  This creates a separate set.  The database port has also been removed from secrets.
- Sync secrets object
- Pointed sync to new object
- Remove port secret, go with visible value instead
---
- [Frontend](https://nr-spar-22-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1472-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1472-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health) …
> chore(ci): sync secrets object

- backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/service/OrchardService.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/service/SparBecCatalogueService.java
- fixed a problem where bec zone code with null values crashes the oracle' orchard endpoint
- update seedlot table's timestamp when draft table is updated
---
- [Frontend](https://nr-spar-27-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1477-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1477-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: orchard null bec zone code and draft timestamp

- .github/workflows/.deploy.yml
Sync has not been getting updated property in the TEST workflow.  That was due to environments being inconsistently set.  This PR applies environments at the workflow/top level, making these mistakes harder to repeat.
- Environment handling in .deploy.yml
---
- [Backend](https://nr-spar-1482-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1482-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …
> fix(ci): set environment at top level

- .github/workflows/.deploy.yml
Reverses a PR based around an AI-hallucination around top/workflow scoped environments.
- "Normal" environment handling that actually exists
---
- [Backend](https://nr-spar-1483-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1483-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): recover from AI-hallucinated top-level envs

- .github/workflows/.deploy.yml
Closes nothing, but frees up resources.
- MAX_REPLICAS down from 2 to 1, affecting backend, frontend and oracle-api in PRs
---
- [Frontend](https://nr-spar-36-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1486-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1486-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): MAX_REPLICAS=1 for PRs

- backend/src/main/resources/db/migration/V44__expire_f8_gametic_option.sql
Make F8 gametic option expired as requested by the P.O.
---
- [Backend](https://nr-spar-1494-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1494-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: expire F8 gametic option

- .github/workflows/pr-open.yml
- backend/openshift.deploy.yml
- database/openshift.deploy.yml
- frontend/openshift.deploy.yml
- oracle-api/openshift.deploy.yml
Closes #1288.  The autoscaler, for now, will add pods when CPU or memory utilization hits 80%
- Resources, scaling
---
- [Frontend](https://nr-spar-25-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1475-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1475-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): resources and scaling

- backend/src/main/java/ca/bc/gov/backendstartapi/config/Constants.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
- backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormServiceTest.java
- backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotServiceTest.java
- frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
- frontend/cypress/e2e/smoke-test/seedlot-dashboard.cy.ts
- frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
- frontend/src/components/SeedlotReviewSteps/AuditInfo/index.tsx
- frontend/src/utils/DateUtils.ts
- frontend/src/views/Seedlot/SeedlotRegFormClassA/RegPage.tsx
- frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
Closes #1478 
All cypress tests passed locally
- none
- newly created seedlots are in INC status, once user do a save on the form, the status will be come pending
- When tsc admin refuse or approve a seedlot, update the draft table 
- None
---
- [Backend](https://nr-spar-1497-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1497-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …
> fix: inc seedlot status and draft update

- .github/workflows/.deploy.yml
Closes nothing, but still useful!
- TEST_MODE=true for PRs, else false
---
- [Frontend](https://nr-spar-1-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1501-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1501-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): only PRs use TEST_MODE=true

- .github/workflows/.deploy.yml
- common/openshift.init.yml
- frontend/openshift.deploy.yml
Handling around a var->secret change
- Use init to handle secret that was a var
---
- [Backend](https://nr-spar-1504-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1504-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): move vite_user_pools_web_client_id to init

- database/openshift.deploy.yml
Dial up TEST and PROD PVCs from 1/4 to 1 Gb.
- Larger PVC size for DB
---
- [Frontend](https://nr-spar-9-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1509-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1509-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): dial up TEST and PROD DB PVCs

- .github/workflows/.deploy.yml
- .github/workflows/demo.yml
- .github/workflows/job-sync.yml
- .github/workflows/pr-open.yml
- sync/Dockerfile
- sync/oc_run.sh
- sync/openshift.deploy.yml
Build numbers still aren't showing up in the ETL sync job.  I'm trying to fix that!
---
- [Backend](https://nr-spar-1502-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1502-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): build_number var in sync

- .github/workflows/.deploy.yml
- backend/openshift.deploy.yml
- database/openshift.deploy.yml
- frontend/Dockerfile
- frontend/openshift.deploy.yml
- oracle-api/openshift.deploy.yml
Set TEST and PROD replicas to 3 min and 5 max for backend, frontend and oracle-api.  Loosen liveness probes for the database, because it reboots too easily when busy.
---
- [Frontend](https://nr-spar-10-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1510-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1510-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): set minimum replicas and loosen liveness probes

- sync/config/SQL/SPAR/POSTGRES_SEEDLOT_EXTRACT.sql
When collection start or end date return empty string from json query, pg will not cast to date. 
-
-
-
---
- [Frontend](https://nr-spar-8-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1508-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1508-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: fix empty string for json dates

- database/init_db/init.sql
Fix another db init issue - missing ; on creation of etl_execution_log_hist
-
-
-
> ffeat: fix db init for etl_execution_log pt2

- .github/workflows/.deploy.yml
- .github/workflows/job-sync.yml
- sync/oc_run.sh
- sync/openshift.deploy.yml
Disable ETL retries.  Kicking up an error is good enough.
---
- [Backend](https://nr-spar-1515-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1515-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): disable etl retries, script revisions

- database/openshift.deploy.yml
Increases the site of TEST and PROD's DB PVCs to 1.8 GB.  Total for namespace is 2 GB.  Note TEST PVC will have to be deleted to size-up.
---
- [Backend](https://nr-spar-1518-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1518-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): increase TEST and PROD DB PVCs

- .github/workflows/job-sync.yml
Missing checkout on ETL run.  Whoops.
---
- [Frontend](https://nr-spar-22-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1522-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1522-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): missing checkout for ETL run

- .github/workflows/job-sync.yml
- .github/workflows/release.yml
- sync/oc_run.sh
Enables ETL for PROD, right after running in TEST.
---
- [Backend](https://nr-spar-1533-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1533-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): PROD ETL

- .github/workflows/job-sync.yml
- move environment calls to job, not step level
- run TEST and PROD ETL in parallel, so TEST can't block PROD
- ^ note: we want blocking eventually! ^
---
- [Frontend](https://nr-spar-37-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1537-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1537-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): run ETL on TEST and PROD in parallel, not series

- sync/config/SQL/SPAR/POSTGRES_SEEDLOT_EXTRACT.sql
- sync/config/SQL/SPAR/POSTGRES_SEEDLOT_OWNER_QUANTITY_EXTRACT.sql
Some numeric values returned from json such as collection volume as being interpreted as empty string when missing.
Tested locally.
-
-
-
---
- [Frontend](https://nr-spar-40-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1540-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1540-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: empty strings returned for json numerics

- backend/openshift.deploy.yml
- frontend/openshift.deploy.yml
- oracle-api/openshift.deploy.yml
Hopefully fixes the case where PR images don't update.
- Randomly generated deployment envars to force updates
---
- [Backend](https://nr-spar-1544-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1544-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix(ci): force deployments updates

- .github/workflows/.deploy.yml
- Scales oracle-api instances from 1 to 3/5 min/max in PROD
---
- [Backend](https://nr-spar-1597-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1597-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): set PROD oracle-api replicas to 3-5

- backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
- backend/src/test/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelperTest.java
Closes #1600
- UserAuthenticationHelper to handle long usernames.
---
- [Backend](https://nr-spar-1604-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1604-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: handle long length usernames

- frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
Closes #1635
- added useBlocker logic to seedlot review screen
- None
- None
---
- [Frontend](https://nr-spar-36-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1636-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1636-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: block navigation while in edit mode

- .github/workflows/.deploy.yml
Closes no issue.
This version bump may fix what's happening on this workflow:
Link: https://github.com/bcgov/nr-spar/actions/runs/11077437012
```
/home/runner/work/_temp/02c06dd3-dea5-4825-980c-87e60b2586c2.sh: line 5: oc: command not found
Error: Process completed with exit code 127.
```
- action version
---
- [Backend](https://nr-spar-1652-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1652-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
After merge, …
> chore: bump action-deployer-openshift version

- .github/workflows/.tests.yml
- Cypress workflow, making it pass until the team stops to fix it.
---
- [Backend](https://nr-spar-1654-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1654-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> ci: forces cypress to pass for now. Sorry

- .github/workflows/etl-prod.yml
- .github/workflows/etl-test.yml
- Separate TEST and PROD ETL sync jobs
- Two hour intervals, PROD 30 minutes after TEST
- Common TEST and PROD sync job
---
- [Backend](https://nr-spar-1681-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1681-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): split TEST and PROD ETL jobs

- backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/TscAdminEndpoint.java
- backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/TscAdminEndpointTest.java
- frontend/src/api-service/tscAdminAPI.ts
- frontend/src/views/Seedlot/SeedlotDetails/index.tsx
- frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
Closes #1698
- Nothing :)
- Nothing :)
- Removed truncated status
---
- [Backend](https://nr-spar-1699-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1699-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: 1698 changing status when editing seedlot on review page

- sync/src/module/data_synchronization.py
- sync/src/module/database_connection.py
- return db excution result
- adjust ownership logic
---
- [Backend](https://nr-spar-1718-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1718-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: return db excuction result

- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/definitions.ts
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
Closes #1628 
- Added new species to class A seedlots
- Added new GW value to FDI species
- Made all the GW columns appear on the step 5 table
- Nothing :)
---
- [Backend](https://nr-spar-1719-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1719-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: 1628 adjustments to show hide feature step 5

- frontend/src/api-service/ApiConfig.ts
- frontend/src/api-service/seedlotAPI.ts
- frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/index.tsx
- frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
- oracle-api/config/application-local.yml
- oracle-api/src/main/java/ca/bc/gov/oracleapi/endpoint/SeedlotEndpoint.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/entity/Seedlot.java
- oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/SeedlotRepository.java
This pull request introduces a new API endpoint to retrieve seedlot information by seedlot number and integrates this functionality into the frontend. The changes include updates to the API configuration, addition of a new endpoint in the backend, and modifications to the frontend components to utilize this new endpoint.
New
- lock ownership to read only when original qty is over 0
- added new endpoint on oracle db to expose original qty from seedlot table
---
- [Frontend](https://nr-spar-12-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1712-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1712-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
Please …
> feat: 1694 lock ownership to read only

- frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/SingleOwnerInfo/index.tsx
- frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/index.tsx
- frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
Closes #1694 
- Only lock ownership section in review page
---
- [Frontend](https://nr-spar-38-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1738-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1738-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: lock ownership section in review page

- frontend/src/views/Landing/index.tsx
Closes #1722 
- WCAG changes to the Login page
- Login page
- None
---
- [Frontend](https://nr-spar-42-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1742-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1742-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: add HTML semantics

- backend/pom.xml
- oracle-api/pom.xml
- downgrade hibernate version to 6.6.2 final
---
- [Backend](https://nr-spar-1769-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1769-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: downgrade hibernate version to 6.6.2final

- backend/src/main/resources/db/migration/V46__fix_etl_tables.sql
Includes a migration file that will result in new databases created from the migrations to have the same structure as what is currently implemented in our physical TEST / PROD databases.  The migration has conditionals attached which should prevent the existing database from being modified.
Closes #1764
- new migration file
-
-
Tested by running net new migration using local env.  Confirmed that this has the same structure as what exists in the physical implementations of TEST / PROD (spar2).  Then deleted the V46 record from the flyway migration table and re-ran the migrations. This simulates the conditions for running this migration on the physical db's TEST / PROD.  Verified that the migrations did not crash or otherwise alter the structure of the tables.
--- …
> fix: added migration file to fix discrepancies

- frontend/src/components/ClientAndCodeInput/index.tsx
- frontend/src/components/ClientAndCodeInput/styles.scss
- frontend/src/components/InputErrorText/index.tsx
- frontend/src/components/PageTitle/index.tsx
Closes #1724 
- WCAG changes for Create A-class seedlot page
-
-
---
- [Frontend](https://nr-spar-43-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1793-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1793-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: 1724 wcag standards applicant agency

- frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/index.tsx
- frontend/src/views/Seedlot/ContextContainerClassA/context.tsx
- frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
- frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
- frontend/src/views/Seedlot/SeedlotRegFormClassA/RegPage.tsx
Closes #1781 
- Added new control state to show data only when the form data state is fully loaded, avoiding sync errors
- Fixed ownership step initialization for submitted seedlots
- Nothing :)
---
- [Backend](https://nr-spar-1802-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1802-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: 1781 ownership percentage and client number acronym anomalies in migrated data

- frontend/src/components/FavouriteActivities/index.tsx
- frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
- frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
Closes #1740 
- Nothing :)
- The title of the section
- Made a small adjustments on favourites columns
- Where the data is coming from to set the payload after user triggers a recalculation
- Nothing :)
---
- [Backend](https://nr-spar-1814-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1814-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.ym …
> fix: 1740 inaccurate data being shown in review form

- .github/workflows/.deploy.yml
- .github/workflows/.tests.yml
- .github/workflows/analysis.yml
- .github/workflows/merge.yml
- .github/workflows/pr-open.yml
---
- [Backend](https://nr-spar-1817-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1817-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): actions moved to bcgov org

- frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
Closes #1739 
Instead of trying to sync the seedlot data and orchards requests, it was waaaay easier to just change the field displayed to the user.
- Nothing :)
- Validation for the field to be shown for users after the form is submitted
- Nothing :)
---
- [Backend](https://nr-spar-1815-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1815-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …
> fix: 1739 orchard number disappears in form

- backend/pom.xml
- revert hibernate version back to 6.6.2
---
- [Frontend](https://nr-spar-43-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1843-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1843-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> fix: revert hibernate version back to 6.6.2

- .github/workflows/pr-open.yml
- backend/Dockerfile
- frontend/Dockerfile
- oracle-api/Dockerfile
- sync/Dockerfile
- sync/src/main.py
bcgov/action-builder-ghcr already provides BUILDER_TAG and other envars, so let's stop creating our own.
---
- [Frontend](https://nr-spar-8-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1858-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1858-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): use BUILDER_TAG from action, drop our BUILD_NUMBER

- common/openshift.database.yml
TEST and PROD are using 2 Gi of memory, using up all our quota.  It has been dialed down to 512, which is still double the usage being seen.
---
- [Frontend](https://nr-spar-10-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1860-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1860-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): reign in TEST and PROD memory resources

- sync/oc_run.sh
Restore script.  This caused PROD ETL to fail twice.  Sorry @SLDonnelly !
---
- [Backend](https://nr-spar-1920-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1920-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): restore sync cronjob script

- .github/workflows/.deploy.yml
- .github/workflows/pr-open.yml
- backend/openshift.deploy.yml
- common/openshift.init.yml
Tiny change to trigger a backend build and deployment.  Adjust PR memory over-allocations.
---
- [Backend](https://nr-spar-1919-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1919-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore(ci): adjust db RAM, backend params

- frontend/package-lock.json
Reverts bcgov/nr-spar#1928
---
- [Frontend](https://nr-spar-36-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1936-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1936-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> chore: Revert "fix(deps): update dependency axios to v1.8.2 [security]"

- frontend/src/utils/TestActivitiesUtils.ts
- frontend/src/views/CONSEP/TestingActivities/MoistureContent/constants.ts
- frontend/src/views/CONSEP/TestingActivities/MoistureContent/index.tsx
- frontend/src/views/CONSEP/TestingActivities/PurityContent/index.tsx
- frontend/src/views/CONSEP/TestingActivities/SharedConstants.ts
Closes #1988 
- add mc variations to custom some fields for different mc type
---
- [Frontend](https://nr-spar-22.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2072-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2072-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
> feat: 1988 add mc variations to custom some fields for different mc type
