bcgov/nr-spar

.github/workflows/ci.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
backend/Dockerfile
backend/dockerfile-entrypoint.sh
oracle-api/dockerfile-entrypoint.sh

---
[Backend](https://nr-spar-22-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-22-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-22-oracle-api.apps.silver.devops.gov.bc.ca/)

Dockerfile adjustments

---

.github/CODEOWNERS

Plowing this through to allow our repo wrap-up.
---
[Backend](https://nr-spar-46-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-46-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-46-oracle-api.apps.silver.devops.gov.bc.ca/)

Revise CODEOWNERS again

---

README.md
backend/CONTRIBUTING.md
backend/README.md
frontend/CONTRIBUTING.md
frontend/README.md
oracle-api/CONTRIBUTING.md
oracle-api/README.md

Update all three readme files and contributing guides.
Note that the contributing files are just a copy and past from the old repositories. I did a quick update on the readme files though.
No tests are required.
---
[Backend](https://nr-spar-62-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-62-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-62-oracle-api.apps.silver.devops.gov.bc.ca/)

docs: update readme

---

frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
frontend/src/components/SeedlotRegistrationSteps/InterimStep/styles.scss

Upate Interim step with proper labels.
Fixes [Jira Ticket FSADT2-656](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-656)
This change was tested locally.
Current running version (wrong):
⚠️ Note: I grabbed this screenshot from localhost because our test environment is not properly working yet.
Fixed version (according to [Figma design](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=576-382116&t=QbtXmEZrgICoGCB7-0)):
---
[Backend](https://nr-spar-75-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-75-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-75-oracle-api.apps.silver.devops.gov.bc.ca/) …

fix: interim step wrong labels

---

backend/openshift.deploy.yml
database/openshift.deploy.yml
frontend/openshift.deploy.yml
oracle-api/openshift.deploy.yml

This should allow four or five PR deployments at once vs the inconsistent two we had before.  Further quota increases would still be helpful!
---
[Backend](https://nr-spar-90-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-90-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-90-oracle-api.apps.silver.devops.gov.bc.ca/)

Reduce OpenShift CPU and Memory allocations

---

frontend/package.json
frontend/yarn.lock

Renovate branch and would-be upcoming PR.
---
[Backend](https://nr-spar-93-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-93-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-93-oracle-api.apps.silver.devops.gov.bc.ca/)

fix(deps): update dependency @typescript-eslint/parser to v5.59.2

---

.github/CODEOWNERS

---
[Backend](https://nr-spar-110-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-110-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-110-oracle-api.apps.silver.devops.gov.bc.ca/)

Add to .github/CODEOWNERS

---

docker-compose.yml
oracle-api/Dockerfile
oracle-api/dockerfile-entrypoint.sh

Modify Docker configuration of the `oracle-api` module so that the container can connect to the remote database.
For now, such change demands the container to have access to the host network, and the specification of the DNS of the VPN being used (you can get its address by running `nslookup gov.bc.ca | grep -Po 'Server:\s*\K.*$'`, for instance).
Fixes [FSADT2-670](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-670) (partially)
NOTE: Run oracle-api optionally using Docker Compose with `docker compose up oracle-api`.
---
[Backend](https://nr-spar-108-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-108-frontend.apps.silver.devops.gov.b …

build: modify docker configuration for oracle-api

---

.github/workflows/merge-main.yml

OpenShift resources increased.  Dialing up replicas accordingly.
---
[Backend](https://nr-spar-111-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-111-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-111-oracle-api.apps.silver.devops.gov.bc.ca/)

Increase backend and frontend replicas (2 min, 3 max)

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml

Fix main merge for TEST and PROD deployments.
---
[Backend](https://nr-spar-113-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-113-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-113-oracle-api.apps.silver.devops.gov.bc.ca/)

Fix: main merge

---

CONTRIBUTING.md

Add more description and guides for local development, code changes and pull request.
No tests needed.
---
[Backend](https://nr-spar-121-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-121-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-121-oracle-api.apps.silver.devops.gov.bc.ca/)

Docs: improve contributing guide

---

.github/workflows/merge-main.yml
.github/workflows/pr-close.yml

Remove workflow path ignores.  Replacement expected though our custom Actions.
---
[Backend](https://nr-spar-123-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-123-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-123-oracle-api.apps.silver.devops.gov.bc.ca/)

Remove pipeline path ignores

---

frontend/src/views/Seedlot/MySeedlots/SeedlotDataTable/index.tsx
frontend/src/views/Seedlot/SeedlotDetails/index.tsx

Bug fix for two navigation problems (in my seedlots table and in the specific seedlot page)
Fixes [FSADT2-608](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-608) and [FSADT2-617](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-617)
---
[Backend](https://nr-spar-125-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-125-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-125-oracle-api.apps.silver.devops.gov.bc.ca/)

Navigation fixes

---

docker-compose.yml
frontend/Dockerfile.dev
frontend/src/__test__/views/Landing.test.tsx
frontend/src/__test__/views/__snapshots__/Landing.test.tsx.snap
frontend/src/views/Landing/index.tsx

Jira: [FSADT2-670](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-670)
Add front end hot reload function to docker
1. Run with docker compose command
I prefer `docker compose --env-file .env up`, the `.env` file has `FORESTCLIENTAPI_KEY`
Alternatively you can export this env var to your terminal
2. Once the front end container is running, change some text like you would doing front end development, the page should be hot reloaded reflecting the change.
3. Note that the first re-compile is quite slow(at least on my machine), but the subsequent ones are fast 
local
---
[Backend](https://nr-spar-141-backend.apps.silver.devops.gov.bc.ca/) …

feat: add docker hot reload for frontend

---

.github/workflows/pr-open.yml

---
[Backend](https://nr-spar-162-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-162-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-162-oracle-api.apps.silver.devops.gov.bc.ca/)

Bump bcgov-rn/action-builder.ghcr to 1.1.1

---

.github/workflows/pr-open.yml

Bump [bcgov-nr/action-builder-ghcr](https://github.com/bcgov-nr/action-builder-ghcr) action to version 1.1.2.
This change will be tested with this PR
---
[Backend](https://nr-spar-190-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-190-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-190-oracle-api.apps.silver.devops.gov.bc.ca/)

feat: bump action builder ghcr action version

---

backend/Dockerfile.local
backend/dockerfile-entrypoint.sh
backend/pom.xml
docker-compose.yml

Local development in docker-compose.yml for backend.  Includes auto-reload for Java.
---
[Backend](https://nr-spar-195-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-195-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-195-oracle-api.apps.silver.devops.gov.bc.ca/)

feat: backend docker-compose

---

frontend/package.json
frontend/yarn.lock

Copied description from #210 
Afte upgrading typescript to version 5 this error started to appear:
The solution is to update fork-ts-checker-webpack-plugin to 6.5.3, see:
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/797 
With that upgrade we will have to upgrade webpack from this warning:
`warning " > fork-ts-checker-webpack-plugin@6.5.3" has unmet peer dependency "webpack@>= 4".`
local testing
---
[Backend](https://nr-spar-211-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-211-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-211-oracle-api.apps.silver.devops.gov.bc.ca/)
Once merged, code …

fix: upgrade webpack and ts-checked-plugin

---

backend/.mvn/google_checks.xml
backend/pom.xml
backend/src/main/java/ca/bc/gov/backendstartapi/config/NativeImageConfig.java
backend/src/main/java/ca/bc/gov/backendstartapi/config/SecurityConfig.java
backend/src/main/java/ca/bc/gov/backendstartapi/config/SwaggerConfig.java
backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ParentTreesContributionEndpoint.java
backend/src/main/java/ca/bc/gov/backendstartapi/entity/ActiveOrchardSeedPlanningUnit.java
backend/src/main/java/ca/bc/gov/backendstartapi/entity/SmpMix.java
backend/src/main/java/ca/bc/gov/backendstartapi/entity/SmpMixGeneticQuality.java
backend/src/main/java/ca/bc/gov/backendstartapi/entity/idclass/ActiveOrchardSeedPlanningUnitId.java
backend/src/main/java/ca/bc/gov/backendstartapi/entity/idclass/SmpMixId.java
backend/src/test/java/ca/bc/gov/backendstartapi/jpa/SmpMixGeneticQualityJpaTest.java
backend/src/test/java/ca/bc/gov/backendstartapi/jpa/SmpMixJpaTest.java
oracle-api/pom.xml
oracle-api/src/main/java/ca/bc/gov/backendstartapi/config/SecurityConfig.java
oracle-api/src/main/java/ca/bc/gov/backendstartapi/entity/VegetationCode.java

Fix a lot of warnings on backend codebase, making it free of possible issues and errors.
Fixes #244 
This change was tested locally, with Swagger, and with Unit testing. 
---
[Backend](https://nr-spar-245-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-245-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-245-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: warnings on java code

---

frontend/.eslintrc.json

From #253 
> A new eslint rule was enabled through the eslint plugin `jsdoc`, where return values and params need to be specified in block comment. 
> This is not desired in React development as not all block comments are written to describe the inputs and outputs of a function. 
> ![image](https://github.com/bcgov/nr-spar/assets/25162561/be02198d-3334-4ecf-9d67-d7f75370f2c1)
Rules are updated
Not applicable
---
[Backend](https://nr-spar-254-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-254-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-254-oracle-api.apps.silver.devops.gov.bc.ca/)
Once merged, code will be …

fix: disable requirements in eslint rules

---

backend/Dockerfile.local
backend/README.md
docker-compose.yml
frontend/README.md

- Add backend API Remote Debug option (using port 5005).
- Update README files to include new local containerized applications.
Fixes #303 
This was tested locally.
Here's how you can test:
- Starting frontend will get required services up and running as well, like backend and database.
- Run: `docker compose up frontend -d`
- Wait for all services get up and healthy
- Change anything in frontend or backend
- Enjoy
if you want to debug the backend, please, follow the instructions on the backend/README file.
---
[Backend](https://nr-spar-304-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-304-frontend.apps.silver.devops.gov.bc.ca/) …

feat: add backend debug option to container

---

frontend/src/components/PanelSectionName/styles.scss
frontend/src/theme/components-overrides.scss

fixing the bug that when the page height is decreased and the scrollbar appears, the borders of the panel section name keep showing.
Fixes #[198](https://github.com/bcgov/nr-spar/issues/198)
Manualy tested.
---
[Backend](https://nr-spar-291-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-291-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-291-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: 198 broken border

---

.github/workflows/ci.yml
README.md

Readme badges.  Closes https://github.com/bcgov/nr-spar/issues/36 and a bit more.
---
[Backend](https://nr-spar-325-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-325-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-325-oracle-api.apps.silver.devops.gov.bc.ca/)

Readme badges

---

backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/MaleFemaleMethodologyEndpoint.java
backend/src/main/java/ca/bc/gov/backendstartapi/enums/MaleFemaleMethodologyEnum.java
backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/MaleFemaleMethodologyEndpointTest.java
frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx

Adjusted the flag name on the frontend and swagger documentation. 
Fixes # (issue)
Tested manually.
---
[Backend](https://nr-spar-330-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-330-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-330-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: adjusting 'isPLI' flag name

---

.github/workflows/pr-open.yml

Update action.  Remove conditional, since duplications are now better handled (hopefully).

ci: bump action-pr-description-add

---

frontend/package.json
frontend/yarn.lock

Reverts bcgov/nr-spar#354
could not figure out why the errors are here
---
[Backend](https://nr-spar-362-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-362-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-362-oracle-api.apps.silver.devops.gov.bc.ca/)

Revert "chore(deps): update linters to v6 (major)"

---

frontend/package.json
frontend/yarn.lock

Revert "fix(deps): update dependency @typescript-eslint/parser to v5.62.0"

---

.github/CODEOWNERS

Adding myself to CODEOWNERS and participating a little more again!  :)
---
[Backend](https://nr-spar-407-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-407-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-407-oracle-api.apps.silver.devops.gov.bc.ca/)

CODEOWNERS + DerekRoberts (me)

---

frontend/Caddyfile
frontend/Dockerfile
frontend/openshift.deploy.yml
frontend/src/__test__/components/__snapshots__/BCHeader.test.tsx.snap
frontend/src/components/BCHeader/index.tsx

Replaces react-serve with Caddy static web server.
Fixes #161 
This was tested locally and with Docker containers.
---
[Backend](https://nr-spar-406-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-406-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-406-oracle-api.apps.silver.devops.gov.bc.ca/)

feat: replace react-serve with caddy

---

.github/workflows/pr-open.yml

Bump.
---
[Backend](https://nr-spar-411-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-411-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-411-oracle-api.apps.silver.devops.gov.bc.ca/)

ci: update action-pr-description-add to 1.0.1

---

.github/workflows/ci.yml

Update required.  Warning:
```
The version of Java (11.0.17) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
```
---
[Backend](https://nr-spar-427-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-427-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-427-oracle-api.apps.silver.devops.gov.bc.ca/)

deps: bump action-test-and-analyse

---

backend/src/main/resources/logback-spring.xml
database/openshift.deploy.yml

- Add missing date information on local logs
- Increase database memory limit
Tested locally.
---
[Backend](https://nr-spar-432-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-432-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-432-oracle-api.apps.silver.devops.gov.bc.ca/)

feat: increase database memory limit and add missing date to logs

---

.github/workflows/merge-main.yml

I missed a namespace var.  Whoops.  :/
---
[Backend](https://nr-spar-433-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-433-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-433-oracle-api.apps.silver.devops.gov.bc.ca/)

bug: clip one last namespace var

---

.github/workflows/ci.yml
.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
common/openshift.init.yml
frontend/CONTRIBUTING.md
frontend/Caddyfile
frontend/README.md
frontend/openshift.deploy.yml

---
[Backend](https://nr-spar-442-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-442-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-442-oracle-api.apps.silver.devops.gov.bc.ca/)

bug: frontend to caddy cors stops

---

docker-compose.yml

Fix frontend docker compose health check.
This change handles the issue of running the frontend locally with docker compose and having the frontend container health check failing even though it's working.
Tested locally.
---
[Backend](https://nr-spar-482-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-482-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-482-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: update frontend health check on dockercompose

---

docker-compose.yml
frontend/package-lock.json

I changed our Docker base images, but forgot to make a correction to docker-compose.yml.  This is the fix.
---
[Backend](https://nr-spar-511-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-511-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-511-oracle-api.apps.silver.devops.gov.bc.ca/)

bug: frontend deploy issues

---

.github/workflows/ci.yml

---
[Backend](https://nr-spar-519-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-519-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-519-oracle-api.apps.silver.devops.gov.bc.ca/)

ci: bump Trivy action

---

.github/workflows/ci.yml
.github/workflows/cypress-nightly.yml
.github/workflows/merge-main.yml
.github/workflows/pr-open.yml

---
[Backend](https://nr-spar-520-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-520-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-520-oracle-api.apps.silver.devops.gov.bc.ca/)

ci: bump checkout action

---

docker-compose.yml

```
healthcheck:
test: timeout 10s bash -c 'true > /dev/tcp/127.0.0.1/3000'
```
---
[Backend](https://nr-spar-523-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-523-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-523-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: Compose healthcheck w/ no curl or bash

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
backend/openshift.deploy.yml
backend/openshift.fluentbit.yml
database/openshift.deploy.yml
frontend/openshift.deploy.yml
oracle-api/openshift.deploy.yml

Goodbye (so far):
- PROMOTE variables
---
[Backend](https://nr-spar-524-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-524-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-524-oracle-api.apps.silver.devops.gov.bc.ca/)

chore: devops simplication and revisions

---

frontend/cypress.config.ts
frontend/cypress/constants.ts
frontend/cypress/e2e/smoke-test/create-a-class-seedlot.cy.ts
frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
frontend/cypress/e2e/smoke-test/login-page.cy.ts
frontend/cypress/e2e/smoke-test/seedlot-main-page.cy.ts
frontend/cypress/support/commands.ts

Implements #531 
To reduce the test flakiness, we are adding 2 retries to cypress tests upon failure.
Logging in appears to be the most time consuming process of our tests, thus `cacheAcrossSpecs: true,` is added to the `cy.session()` command in our `cy.login()`. 
This enables the session to be kept alive across multiple specs, meaning the entire cypress flow only needs to be logged in **once**. 
Removed a lot of `cy.wait()` since our usage is an anti pattern. See the reason and best practice here: https://docs.cypress.io/guides/references/best-practices#Unnecessary-wait-for-cyrequest
We used `cy.wait()` to wait for a page load or redirect, the best practice is to use 
`cy.url().should('contains', <relative url>)` <- this will wait for as long as the condition is met and up to 10 seconds, …

feat: optimize cypress

---

backend/src/main/resources/logback-spring.xml

Add WARN and ERROR levels to file appender, so we can send them to OpenSearch.
This will be tested with this PR.
---
[Backend](https://nr-spar-543-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-543-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-543-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: add warn and error logs to file

---

.github/workflows/pr-open.yml
database/Dockerfile

---
[Backend](https://nr-spar-545-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-545-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-545-oracle-api.apps.silver.devops.gov.bc.ca/)

Bump Postgres from 13 to 15

---

database/openshift.deploy.yml

---
[Backend](https://nr-spar-550-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-550-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-550-oracle-api.apps.silver.devops.gov.bc.ca/)

ci: extend database timeout seconds

---

.github/workflows/pr-open.yml
frontend/Dockerfile

---
[Backend](https://nr-spar-576-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-576-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-576-oracle-api.apps.silver.devops.gov.bc.ca/)

deps: update action-test-and-analyse

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

Update Keycloak SSO authentication realm URL for PROD.
Fixes #553 
This can only be tested once merged.
---
[Backend](https://nr-spar-580-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-580-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-580-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: wrong keycloak realm url for prod

---

.github/workflows/pr-open.yml
backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java

Remove the condition avoiding the pagination index starting at zero, because that's actually zero-based. 
Fixes #582 
Tested locally with Swagger.
---
[Backend](https://nr-spar-584-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-584-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-584-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: spring pagination is zero-based

---

frontend/package-lock.json
frontend/package.json

https://github.com/bcgov/nr-spar/security/dependabot/48
---
[Backend](https://nr-spar-599-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-599-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-599-oracle-api.apps.silver.devops.gov.bc.ca/)

deps: update babel for subdep vulnerability

---

frontend/package-lock.json
frontend/package.json

https://github.com/bcgov/nr-spar/security/dependabot/45
---
[Backend](https://nr-spar-601-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-601-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-601-oracle-api.apps.silver.devops.gov.bc.ca/)

deps: vitest for subdep get-func-name vulerability

---

frontend/package-lock.json
frontend/package.json

https://github.com/bcgov/nr-spar/security/code-scanning/62
https://github.com/bcgov/nr-spar/security/dependabot/46
---
[Backend](https://nr-spar-606-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-606-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-606-oracle-api.apps.silver.devops.gov.bc.ca/)

Use override to bring postcss up to patched ver

---

.github/workflows/ci.yml
.github/workflows/pr-open.yml

---
[Backend](https://nr-spar-651-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-651-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-651-oracle-api.apps.silver.devops.gov.bc.ca/)

ci: test action revisions

---

frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts

Fixes: #546 
Forgot to implement the function to clean SMP mix tab's data (3rd tab on step 5)
Should be working now!
Manual test
---
[Backend](https://nr-spar-661-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-661-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-661-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: clean mix table data

---

frontend/src/components/ApplicantAgencyFields/index.tsx

Quick fix
- ApplicantFields validation logic
---
[Backend](https://nr-spar-696-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-696-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-696-oracle-api.apps.silver.devops.gov.bc.ca/)

fix: remove assertion

---

frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/utils.ts
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/definitions.ts
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
frontend/src/views/Seedlot/SeedlotRegistrationForm/utils.ts

Closes #695
The issue was intended to refactor the first 2 tabs of step 5 only, it turned out it's easier to just refactor the mix tab as well. So this PR refactors all 3 tabs.
- Changed RowItem's type definition from `''` to `StringInputType`
- Refactored the rudimentary Validation logic in step 5 
- Lots of the changes you'll see are just typescript gymnastic
- In `SeedlotRegistrationForm`, the initializing functions inside the useState for `allStepData` were actually being called on every render 🤦‍♂️. This was fixed by encapsulating the object inside a `( )=>{ }`
- Introduced some new types inside the definition file of the ParentTreeStep, these were used for typescript gymnastic. Previously, the RowItem has a `[key: string]: any` defined inside, this sort of makes the type useless as …

feat: refactor step 5 1-3 input storage type

---

.github/workflows/ci.yml
.github/workflows/pr-open.yml

---
[Backend](https://nr-spar-27-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-27-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-27-oracle-api.apps.silver.devops.gov.bc.ca/)

chore(ci): revise PR numbers for FAM

---

frontend/Dockerfile

Closes #562 
- Added missing `public` folder copy on `Dockerfile`.
- Dockerfile
- Nothing
No post-deployment tasks required.
---
[Frontend](https://nr-spar-32-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-32-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-32-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: manifest json file not found

---

frontend/Caddyfile

https://github.com/bcgov/nr-spar/issues/118
---
[Frontend](https://nr-spar-49-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-49-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-49-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: Caddy return 404, still redirect

---

.github/workflows/merge.yml

---
[Frontend](https://nr-spar-7-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-7-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-7-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): main merge verification_path

---

backend/pom.xml

---
[Frontend](https://nr-spar-25-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-25-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-25-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

deps: backend springboot

---

frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/index.tsx
frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx

Closes [#763](https://github.com/bcgov/nr-spar/issues/763)
- None
- Autocomplete prop in camelcase to remove warning
- None
---
[Frontend](https://nr-spar-39-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-39-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-39-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: autocomplete in camelcase

---

frontend/Caddyfile

Adjust Caddyfile.  Merge and verify on TEST.

chore(ci): caddyfile adjustments

---

backend/src/main/java/ca/bc/gov/backendstartapi/entity/SeedlotSeedPlanZoneEntity.java
backend/src/main/resources/db/migration/V25__add_cols_to_seedlot_spz.sql

Closes #830
- Migration file to add 2 columns
- the SPZ table entity 
- None
---
[Frontend](https://nr-spar-45-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-45-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-45-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: add SPZ columns on the seedlot seed plan zone table

---

backend/README.md
backend/pom.xml
backend/src/main/java/ca/bc/gov/backendstartapi/config/SecurityConfig.java
backend/src/main/java/ca/bc/gov/backendstartapi/config/SecurityConfigDev.java
backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
backend/src/main/resources/application.properties
backend/src/main/resources/docker-compose-dev.yml
backend/src/main/resources/logback-spring.xml

Closes #672
- docker compose for dev local, allowing devs run java backend quickly, containerized and with postgres db.
- Configuration file disabling authentication when running with dev profile
- User Authentication class identifying local dev user
- None;
Here's how you can test it:
1. Get into the backend directory (`cd backend` from the project root)
2. Run `./mvnw spring-boot:run -Pdocker-compose -Dspring-boot.run.profiles=docker-compose`
No post-deployment tasks required;
---
[Frontend](https://nr-spar-1-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-1-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-1-oracle-api.apps.silver.devops.gov.bc. …

feat: add native support for docker compose to postgres-api

---

backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotFormSubmissionDto.java
backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotFormPutTest.java
frontend/src/types/SeedlotType.ts
frontend/src/views/Seedlot/SeedlotRegFormClassA/index.tsx
frontend/src/views/Seedlot/SeedlotRegFormClassA/utils.ts

Closes #844 
- Added new parameter for smp data submission
- Nothing :)
- Nothing :)
---
[Frontend](https://nr-spar-9-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-9-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-9-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: 844 fix SMP Mix data submission

---

backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
backend/src/main/java/ca/bc/gov/backendstartapi/exception/SeedlotOrchardNotFoundException.java
backend/src/main/java/ca/bc/gov/backendstartapi/repository/SeedlotSeedPlanZoneRepository.java
backend/src/main/java/ca/bc/gov/backendstartapi/service/OrchardService.java
backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpointTest.java
backend/src/test/java/ca/bc/gov/backendstartapi/service/OrchardServiceTest.java
backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotFormPutTest.java
backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotServiceTest.java

Closes #816 
- Methods on the `SeedlotEndpoint` and `SeedlotService` classes;
- Some refactoring to attent the DRY pattern. (Don't repeat yourself)
- None;
No post-deployment tasks required.
---
[Frontend](https://nr-spar-18-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-18-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-18-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: create SPZ endpoint given a seedlot number

---

frontend/cypress.config.ts
frontend/cypress/e2e/smoke-test/login-page.cy.ts
frontend/cypress/support/commands.ts
frontend/src/contexts/AuthProvider.tsx

Closes #446 
- None
- Frontend `AuthProvider`;
- None
No post-deployments tasks.
---
[Frontend](https://nr-spar-12-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-12-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-12-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: handle test login for business bceid between legacy and new spar

---

.github/workflows/pr-open.yml
common/openshift.fluentbit.yml
database/openshift.deploy.yml

---
[Frontend](https://nr-spar-21-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-21-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-21-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): allow autoscaling in PRs, some simplification

---

backend/src/main/resources/db/migration/V26__create_seedlot_audit_table.sql
backend/src/main/resources/db/migration/V27__create_seedlot_audit_trigger.sql

Closes #858 
- Just DB artifacts
- Including new data artifacts: seedlot_audit table, trigger trg_seedlot_audit_DIU and function spar.seedlot_if_modified_func
-
Unit tests
No
---
[Frontend](https://nr-spar-4-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-4-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-4-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Including Seedlot audit table with Triggers

---

.github/workflows/pr-close.yml
oracle-api/src/main/java/ca/bc/gov/backendstartapi/config/SwaggerConfig.java

minute change to test oracle deployment
---
[Frontend](https://nr-spar-35-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-35-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-35-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: update link on swagger

---

.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
common/openshift.fluentbit.yml

No issue related.
- None.
- Pr-close workflow.
- None.
---
[Frontend](https://nr-spar-2-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-952-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-952-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: remove unexisting job

---

backend/src/main/resources/db/migration/V30__include_approved_date_userid_in_seedlot_and_audit_tables.sql

Including approved_timestamp and approved_userid into seedlot table and seedlot_audit table.
Updating trigger to include some missing fields to be updated in the audit table
Closes #850 
-
-
-
---
[Frontend](https://nr-spar-14-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-964-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-964-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: Including new approved_date and user_id into Seedlot table and Audit table and trigger

---

.github/workflows/pr-open.yml

---
[Frontend](https://nr-spar-19-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-969-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-969-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): tag_fallback

---

.github/workflows/merge.yml

---
[Frontend](https://nr-spar-22-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-972-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-972-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): main merge tags

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

* deploy components conditionally
* run cypress only when deployments have happened
* run init and builds in parallel
* PR summary step to simplify pass conditions and handle skips
* workflow dispatch for main with PR or TAG as optional input

fix(ci): checks, conditionals and main workflow dispatch

---

.github/workflows/.tests.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml
frontend/tsconfig.json

Frontend tests are only running in PRs, so there's no main comparison to work with.  Comes with a pile of updates, mostly around shared jobs.
---
[Frontend](https://nr-spar-35-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-985-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-985-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
[Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

fix: frontend sonar cloud

---

.github/workflows/merge.yml

Variable bug in main merge cypress tests.

fix(ci): var in main.yml cypress

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

---
- [Frontend](https://nr-spar--frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-995-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-995-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): workflow updates

---

.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/scheduled.yml

Scheduled workflow:
- purge pr deployments after 1 week
- tests
- zap
---
- [Frontend](https://nr-spar--frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1008-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1008-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): scheduled job

---

frontend/src/contexts/AuthProvider.tsx

fix fam
---
- [Backend](https://nr-spar-1020-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1020-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: parse new fam roles

---

backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/TscAdminEndpoint.java
backend/src/main/java/ca/bc/gov/backendstartapi/service/TscAdminService.java
backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/TscAdminEndpointTest.java
backend/src/test/java/ca/bc/gov/backendstartapi/service/TscAdminServiceTest.java

Closes #852 
- API on the TSC Endpoint class allowing Seedlots approvals or disapprovals.
- TSC Admin Endpoint class;
- None;
---
[Frontend](https://nr-spar-4-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-1004-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-1004-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
[Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)
---
- [Frontend](https://nr-spar--frontend.apps.silver.devops.gov.bc.ca/)
- …

feat: api for Seedlot approval or disapproval by the TSC Admin

---

backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/TscAdminEndpoint.java

Closes no issue
- none
- TSC Admin role name;
- None
---
- [Frontend](https://nr-spar-43-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1043-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1043-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: change role name

---

frontend/src/components/BCHeader/styles.scss

Thanks @mmarsoleta for identifying the bug 😂
The profile panel is now scrollable for smaller screens 
---
- [Backend](https://nr-spar-1052-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1052-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: make profile and notification panel scrollable

---

backend/.dockerignore

---
- [Frontend](https://nr-spar-3-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1053-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1053-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(deps): oracle base

---

frontend/src/components/OrganizationSelection/index.tsx

Fixed an issue where forest clients are re-fetched on every profile panel open
---
- [Backend](https://nr-spar-1054-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1054-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: repeated fc calls

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

Removes toUpperCase() from main merge, which had been causing a break.

fix(ci): merge break on toUpperCase()

---

.github/workflows/merge.yml

---
- [Backend](https://nr-spar-1081-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1081-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): remove env.target where not allowed

---

frontend/package-lock.json
frontend/package.json

Reverts bcgov/nr-spar#1115
---
- [Backend](https://nr-spar-1117-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1117-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: Revert "fix(deps): update dependency web-vitals to v4"

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

No issue.  Fix after failed PR merged anyway.
- Improved PR verification checks
---
- [Backend](https://nr-spar-1118-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1118-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): improve results jobs/blocks

---

frontend/package-lock.json

Reverts bcgov/nr-spar#1116
---
- [Backend](https://nr-spar-1120-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1120-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: Revert "chore(deps): lock file maintenance"

---

docker-compose-test.yml
docker-compose.yml

Closes #1105 1105
- Remove version params from docker-compose files
---
- [Frontend](https://nr-spar-21-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1121-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1121-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): dc version is obsolete

---

sync/config/SQL/SPAR/ORACLE_SEEDLOT_EXTRACT.sql
sync/src/main.py
sync/src/module/database_connection.py

Towards https://github.com/bcgov/nr-spar/issues/1087
- reduce chunk split sizes
- improve memory utilization
- turned up log level
---
- [Frontend](https://nr-spar-24-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1124-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1124-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: chunk split and logging

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
common/openshift.init.yml

Closes https://github.com/bcgov/nr-spar/issues/1087
Enables ETL and verifies completion in the deployer with `etl: true`.
- ETL easily enabled and verified
---
- [Frontend](https://nr-spar-23-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1123-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1123-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
Deployments, as required, …

feat(ci): enable ETL w/ param in deployer

---

.github/workflows/.deploy.yml
docker-compose.data.yml
sync/Dockerfile
sync/openshift.deploy.yml
sync/src/main.py

Closes #1148
- Missing Dockerfile files
- Disabled test mode (TEST_MODE=0)
---
- [Backend](https://nr-spar-1149-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1149-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: Dockerfile for ETL Tool deployment

---

.github/workflows/merge.yml

Closes no issue, but aims to fix this failing workflow: https://github.com/bcgov/nr-spar/actions/runs/9116586211
- None
- merge.yml workflow file
- None
---
- [Backend](https://nr-spar-1152-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1152-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: remove test parameter since there's no test input on merge workflow

---

frontend/src/components/ApplicantAgencyFields/index.tsx
frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/index.tsx
frontend/src/views/Seedlot/ContextContainerClassA/definitions.ts
frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
frontend/src/views/Seedlot/ContextContainerClassA/utils.ts

Closes #1175
- New type to deal with forest clients
- Updated the request for forest clients and mapped them, so it's easier to fill form data
- No longer necessary API calls
---
- [Frontend](https://nr-spar-27-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1177-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1177-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: 1175 refactor client and location logic

---

tools/pg-test-portforward.sh

No issue related;
- Bash script to connect on OpenShift Postgres DB;
- None;
- None;
---
- [Backend](https://nr-spar-1184-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1184-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: add test db script

---

.github/workflows/.deploy.yml
.github/workflows/.tests.yml

- add params to extend backend verification seconds and retries
---
- [Backend](https://nr-spar-1194-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1194-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
- [Frontend](https://nr-spar-44-frontend.apps.silver.devops.gov.bc.c …

chore(ci): add backend verification waits/retries

---

frontend/src/api-service/forestClientsAPI.ts

Restoring fc client api
---
- [Backend](https://nr-spar-1202-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1202-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: restore fc client api

---

.github/workflows/.deploy.yml
sync/openshift.deploy.yml

Closes nothing!
- TEST_MODE=0 from 1 for ETL/sync
---
- [Frontend](https://nr-spar-16-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1216-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1216-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): ETL TEST_MODE=0

---

.github/workflows/pr-validate.yml

- Changed PR description backend link from /health/api to /swagger-ui/index.html
---
- [Backend](https://nr-spar-1218-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1218-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): point backend PR link to swagger

---

backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
backend/src/test/java/ca/bc/gov/backendstartapi/service/SeedlotFormPutTest.java

Closes #1201
- Added new function to set data on seedlot
- Nothing :)
- Nothing :)
---
- [Backend](https://nr-spar-1214-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1214-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
- …

feat: 1201 adding submit daclaration info

---

frontend/package-lock.json
frontend/package.json

Closes #1229 and security alerts:
- https://github.com/bcgov/nr-spar/security/code-scanning/101
- https://github.com/bcgov/nr-spar/security/code-scanning/102
- https://github.com/bcgov/nr-spar/security/code-scanning/103
- https://github.com/bcgov/nr-spar/security/dependabot/74
- https://github.com/bcgov/nr-spar/security/dependabot/75
- https://github.com/bcgov/nr-spar/security/dependabot/76
- dependency versions
---
- [Frontend](https://nr-spar-38-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1238-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1238-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
Please create PRs in draft mode.  Mark as ready to …

chore(deps): ws alerts

---

docker-compose.yml

Run pgadmin in Compose with: `docker compose up pgadmin`
- added pgadmin to docker-compose.yml
---
- [Backend](https://nr-spar-1244-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1244-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: Added pgadmin to compose

---

frontend/package-lock.json

this fixes the issue with the orchard combobox
---
- [Backend](https://nr-spar-1265-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1265-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: revert lock file change to d0c79f56fb8ec57a9f3d66bf2162f9b9b57e2184

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
backend/src/main/resources/application.properties
common/openshift.fluentbit.yml
oracle-api/src/main/resources/application.properties

Closes No issue;
- Upgrade ECS (Elastic Common Schema) from version 8.8 to 8.11;
- Upgrade FluentBit version from 2.1 to 3.0;
- Add input variable to match target environment when deploying;
- `log_env_target` variable on `.deploy.yml` file;
- `merge.yml` file adding new variable accordingly to environment;
- None;
---
- [Frontend](https://nr-spar-27-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1277-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1277-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health) …

feat: update opensearch configs & fix environment not working

---

frontend/package-lock.json
frontend/package.json

Closes #948 
---
- [Frontend](https://nr-spar-37-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1287-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1287-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(deps): override braces from 3.0.2 to 3.0.3 for alert

---

frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
frontend/src/views/Seedlot/SeedlotDetails/index.tsx

Revert "fix: enable seedlot review button"

---

.github/workflows/.deploy.yml
.github/workflows/.tests.yml
backend/openshift.deploy.yml
frontend/openshift.deploy.yml

- None;
- deploy yml file adding PR, TEST and PROD cases for Oracle instance.
- OpenShift backend deployment yml making Oracle server URL required;
- OpenShift frontend deployment yml making Oracle server URL required;
- None.
---
- [Backend](https://nr-spar-1314-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1314-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …

feat: update oracle instance target accordingly to environment

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml

Closes #1309 
- None
- init job environment rule;
- None
---
- [Backend](https://nr-spar-1315-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1315-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: test deployments

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
common/openshift.init.yml
oracle-api/openshift.deploy.yml
oracle-api/src/main/resources/application.properties
sync/openshift.deploy.yml

Closes no issue
- None;
- oracle api application propperties.
- None;
---
- [Backend](https://nr-spar-1317-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1317-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: oracle dialect

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml
backend/openshift.deploy.yml
common/openshift.init.yml
database/openshift.deploy.yml
frontend/openshift.deploy.yml
oracle-api/openshift.deploy.yml

Container startups are inconsistently failing.  This is an attempt to better configure them.
- Startup probes
- Named ports
- Timeout and retry values
- Move database to prerequises, parallel to init
- Move PR number pickup out of .deploy.yml
---
- [Backend](https://nr-spar-1332-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1332-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
- [Merge …

chore(ci): revisit probes

---

.github/workflows/.deploy.yml

Closes #issue
-
-
-
---
- [Frontend](https://nr-spar-35-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1335-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1335-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): missing quote

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
common/openshift.fluentbit.yml

Closes #issue
-
-
-
---
- [Frontend](https://nr-spar-36-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1336-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1336-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): params for merge.yml

---

frontend/src/views/Seedlot/ContextContainerClassA/index.tsx

fix a problem where the full form data call isn't being initiated
---
- [Frontend](https://nr-spar-38-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1338-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1338-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: endpoint call trigger

---

frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/constants.ts
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
frontend/src/contexts/AuthProvider.tsx
frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
frontend/src/views/Seedlot/ContextContainerClassA/utils.ts

as title
---
- [Frontend](https://nr-spar-41-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1341-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1341-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: replace toString() with String()

---

.github/workflows/pr-open.yml
database/Dockerfile

Closes #1310 
- Check if builds have been triggered
- Only run deploys and tests if true
---
- [Frontend](https://nr-spar-40-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1340-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1340-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): conditional deployments

---

.github/workflows/.deploy.yml
docker-compose.yml
sync/openshift.deploy.yml

Sync variable revision
- Use true|false for TEST_MODE
- Default TEST_MODE=true everywhere (should eventually change)
- Default EXECUTION_ID=100
---
- [Frontend](https://nr-spar-8-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1358-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1358-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): sync vars

---

sync/openshift.deploy.yml

Closes #issue
-
-
-
---
- [Backend](https://nr-spar-1364-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1364-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): more password revisions

---

backend/src/main/resources/db/migration/V41__update_orchard_spu.sql

Closes No issue
- SQL script migrating Postgres to V41.
- None
- None;
---
- [Backend](https://nr-spar-1368-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1368-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: orchard spu id relationship

---

backend/src/main/resources/db/migration/V42__fix_seedlot_pollen_cont_code.sql
frontend/src/views/Seedlot/ContextContainerClassA/utils.ts

Closes #noissue
- Added new migration file
- Changed pollen methodology code
- Nothing :)
---
- [Frontend](https://nr-spar-28-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1378-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1378-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
- …

fix: changing code

---

.github/workflows/.deploy.yml
.github/workflows/.tests.yml
.github/workflows/cypress-nightly.yml
frontend/CONTRIBUTING.md

To simplify some github secrets have been revised, removed or hard coded.  Lots were related to FluentBit or are similarly out of use.
---
- [Backend](https://nr-spar-1382-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1382-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): straighten out passwords

---

sync/Dockerfile

Closes #issue
-
-
-
---
- [Backend](https://nr-spar-1399-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1399-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: any change to trigger a build for sync

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml
sync/Dockerfile

Closes #issue
-
-
-
---
- [Frontend](https://nr-spar-0-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1400-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1400-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: small changes for visibility and simplicity

---

.github/workflows/.deploy.yml
database/Dockerfile
sync/Dockerfile

Closes #issue
-
-
-
---
- [Frontend](https://nr-spar-3-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1403-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1403-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): update deployer action

---

frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/EditGenWorth.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/PopSize.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/UnrelatedGenWorth.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/definitions.ts
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
frontend/src/types/SeedlotType.ts
frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx

Closes #1374
- Added updates to the correct objects to display GW and NE values
- Fixed the submit values
- Added `wve` genetic worth field
- Nothing :)
- Nothing :)
---
- [Backend](https://nr-spar-1394-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1394-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: 1374 gw and ne not appearing in review and approval screen

---

frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx

Closes #NoIssue
- New key prop inside map
- Nothing :)
- Nothing :)
---
- [Backend](https://nr-spar-1404-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1404-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: adding key prop

---

.github/workflows/cypress-nightly.yml

Closes #issue
-
-
-
---
- [Backend](https://nr-spar-1415-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1415-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): cypress nightly, try 2

---

.github/codeowners
README.md
sync/openshift.deploy.yml

- remove etl oc cronjob, using Actions
- restore Analysis workflow badge
- add @ronrobb to codeowners
---
- [Frontend](https://nr-spar-39-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1439-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1439-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): cleanup

---

.github/workflows/demo.yml

Keep working on workflow triggers.
---
- [Frontend](https://nr-spar-45-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1445-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1445-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
- …

feat(ci): demo routing workflow ii

---

.github/workflows/merge.yml

Deploy to PROD.  Will be revised, since this doesn't have a gate or release trigger.
---
- [Frontend](https://nr-spar-3-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1453-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1453-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): initial PROD deployment

---

.github/workflows/merge.yml
.github/workflows/release.yml

Closes #1441.  After testing with the [previous PR](#1466) this is the follow up that does the actual work.
- PROD pipeline actually deploys
- TEST applies the `prod` label
---
- [Backend](https://nr-spar-1467-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1467-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat(ci): release to prod ii

---

.github/workflows/release.yml

I hate having to merge workflows to test them!!
---
- [Backend](https://nr-spar-1468-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1468-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat(ci): release to prod iii

---

.github/workflows/release.yml

Closes #issue
-
-
-
---
- [Backend](https://nr-spar-1469-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1469-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): quotes

---

.github/workflows/pr-open.yml
sync/Dockerfile
sync/src/main.py

Closes #issue
-
-
-
---
- [Backend](https://nr-spar-1481-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1481-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat(ci): sync build_number envar

---

.github/workflows/.deploy.yml
common/openshift.init.yml

- Deploy yml file
- OpenShift init yml file
---
- [Frontend](https://nr-spar-42-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1492-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1492-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: oracle prod hosts

---

.github/workflows/release.yml
frontend/src/aws-exports.ts

simple fixes
---
- [Frontend](https://nr-spar-5-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1505-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1505-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: release prompt and fam redirect uri

---

.github/workflows/release.yml
frontend/src/aws-exports.ts

fam redirect uri
---
- [Frontend](https://nr-spar-6-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1506-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1506-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: fam redirect uri

---

.github/workflows/pr-close.yml

- added common package to promotions in pr-close.yml
---
- [Frontend](https://nr-spar-7-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1507-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1507-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): add common to pr-close promotions

---

.github/workflows/.deploy.yml

Makes sure sync TEST_MODE=false for PROD.  This is expected to change before long.
---
- [Backend](https://nr-spar-1517-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1517-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): sync test_mode=true for prod

---

.github/workflows/merge.yml

Catches a database promotion I missed.  Whoops.
---
- [Frontend](https://nr-spar-25-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1525-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1525-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): remove straggling database promotion

---

frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx

it's a separate button that will disappear tomorrow
---
- [Frontend](https://nr-spar-26-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1526-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1526-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: separate historical sub to pnd

---

.github/workflows/.deploy.yml
oracle-api/openshift.deploy.yml

TEST_MODE
- PR = true
- TEST = false
- PROD = false
---
- [Backend](https://nr-spar-1531-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1531-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): TEST_MODE=true for PRs only

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml

Restores PROD to main merge.
---
- [Backend](https://nr-spar-1554-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1554-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): restore PROD in main merge

---

legacy_translated/SPR_SEEDLOT.ts

Closes #1555.  CodeQL is choking on a bracket error.  This file is over 7200 lines, so I asked Copilot to find it.  Pretty cool!
---
- [Frontend](https://nr-spar-8-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1558-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1558-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
Deployments, as required, will be available …

fix(ci): SQL formatting for CodeQL

---

.github/workflows/.deploy.yml
oracle-api/openshift.deploy.yml

---
- [Frontend](https://nr-spar-46-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1596-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1596-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: configure different cpu limit in test and prod for oracle api

---

.github/codeowners

- Added @Ding-x to codeowners
- Removed @craigyu from codeowners
---
- [Frontend](https://nr-spar-48-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1598-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1598-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): update codeowners

---

tools/b9d53b-sysdig.yml

Closes #1606 
- Sysdig file under tools
---
- [Frontend](https://nr-spar-11-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1611-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1611-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: add sysdig permission file

---

backend/src/main/java/ca/bc/gov/backendstartapi/service/ParentTreeService.java

Closes no issue.
- `ParentTreeService` class.
---
- [Backend](https://nr-spar-1649-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1649-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: parent tree genetic value calculation fix

---

.github/codeowners

Codeowners changes:
- Removed Ricardo
- Added Kevin
- Updated Xiao
---
- [Backend](https://nr-spar-1682-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1682-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): codeowners updates

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/decision.md
.github/ISSUE_TEMPLATE/epic.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/ux.md

updating Bug ticket to include an impact statement and priority for more transparency and clarity
---
- [Frontend](https://nr-spar-5-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1705-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1705-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: update issue templates

---

.github/workflows/etl-test.yml

---
- [Frontend](https://nr-spar-3-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1703-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1703-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore: update etl-test.yml

---

frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx

Closes #1720
- remove the restriction of editing tpt
---
- [Frontend](https://nr-spar-21-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1721-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1721-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: remove the restriction of editing tpt

---

docker-compose.yml

- revert docker config
---
- [Frontend](https://nr-spar-29-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1729-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1729-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: revert config

---

.github/workflows/pr-open.yml

---
- [Backend](https://nr-spar-1752-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1752-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(ci): catch canceled jobs

---

.github/workflows/analysis.yml

---
- [Backend](https://nr-spar-1833-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1833-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): remove JS handling from workflow conditionals

---

.github/workflows/.deploy.yml
.github/workflows/demo.yml
.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml
.github/workflows/job-nightly.yml
.github/workflows/merge.yml

---
- [Backend](https://nr-spar-1834-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1834-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): use GH runner ubuntu-24.04

---

frontend/src/components/ClientSearchTable/index.tsx
frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx

Closes #1727 
- WCAG accessibility for Step 3 of A-class registration
-
- None
---
- [Frontend](https://nr-spar-30-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1830-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1830-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: 1727 wcag interim storage

---

.github/workflows/.deploy.yml
.github/workflows/.tests.yml
.github/workflows/analysis.yml
.github/workflows/demo.yml
.github/workflows/etl-prod.yml
.github/workflows/etl-test.yml
.github/workflows/job-nightly.yml
.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

* https://github.com/bcgov/nr-spar/security/code-scanning/204
* https://github.com/bcgov/nr-spar/security/code-scanning/205
* https://github.com/bcgov/nr-spar/security/code-scanning/206
* https://github.com/bcgov/nr-spar/security/code-scanning/207
* https://github.com/bcgov/nr-spar/security/code-scanning/208
* https://github.com/bcgov/nr-spar/security/code-scanning/209
* https://github.com/bcgov/nr-spar/security/code-scanning/210
* https://github.com/bcgov/nr-spar/security/code-scanning/211
* https://github.com/bcgov/nr-spar/security/code-scanning/212
* https://github.com/bcgov/nr-spar/security/code-scanning/213
* https://github.com/bcgov/nr-spar/security/code-scanning/214
* https://github.com/bcgov/nr-spar/security/code-scanning/215
* …

chore: alerts

---

frontend/src/views/Seedlot/ContextContainerClassA/utils.ts

Closes #1900
- Added extra validation
- Nothing :)
- Nothing :)
---
- [Frontend](https://nr-spar-1-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1901-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1901-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: 1900 500 Error when submiting seedlot

---

.github/workflows/.deploy.yml

---
- [Backend](https://nr-spar-1917-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1917-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): remove verification params after deployer update

---

backend/src/main/resources/db/migration/V31__add_lat_long_dec_vals_to_seedlot.sql

---
- [Frontend](https://nr-spar-25-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1925-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1925-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(db): create postgis extension in migration

---

frontend/src/App.tsx

Description:
This PR updates the App component to recreate the browserRouter dynamically when signed or selectedClientRoles change. The router is now generated inside a useMemo to reflect the latest authentication and role selection state.
Previously, the router was initialized once on mount, which worked because auth state was usually available immediately. As auth flows became more dynamic or delayed, the static router setup caused routing issues when user state changed after initial load. This fix ensures routes update properly as authentication state changes.
---
- [Backend](https://nr-spar-1934-backend.apps.silver.devops.gov.bc.ca/swagger-ui/ind …

fix: route browser

---

frontend/src/views/CONSEP/TestingActivities/ActivityResult/constants.tsx
frontend/src/views/CONSEP/TestingActivities/ActivityResult/index.tsx
frontend/src/views/CONSEP/TestingActivities/MoistureContent/constants.ts
frontend/src/views/CONSEP/TestingActivities/MoistureContent/index.tsx
oracle-api/src/main/java/ca/bc/gov/oracleapi/service/consep/MoistureContentService.java
oracle-api/src/test/java/ca/bc/gov/oracleapi/service/consep/MoistureContentServiceTest.java

Closes #1972
- generate 4 empty rows for initialization
- show percentage of mc value
- fix seedlot number bug
- category default to QA
- fix date checking bug
---
- [Frontend](https://nr-spar-23-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1973-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1973-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: 1972 optimize mcc

---

frontend/src/views/CONSEP/TestingActivities/ActivityResult/index.tsx
frontend/src/views/CONSEP/TestingActivities/ActivityResult/styles.scss
frontend/src/views/CONSEP/TestingActivities/MoistureContent/constants.ts
frontend/src/views/CONSEP/TestingActivities/MoistureContent/index.tsx
frontend/src/views/CONSEP/TestingActivities/MoistureContent/styles.scss

Closes #1980 
-
- MCC Results table, category section
-
---
- [Frontend](https://nr-spar-35-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1985-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1985-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: 1980 user feedback mcc screen

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml

Make sure PR checks are solid and not accidentally bypassed.
---
- [Frontend](https://nr-spar-46-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1996-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1996-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): tighten PR gates

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml

Closes #issue
-
-
-
---
- [Backend](https://nr-spar-1997-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1997-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): fix gates again

---

.github/workflows/job-nightly.yml
.github/workflows/pr-validate.yml
frontend/openshift.deploy.yml

---
- [Frontend](https://nr-spar-0.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2000-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2000-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): simplify non-PROD frontend URLs

---

.github/workflows/.tests.yml
.github/workflows/analysis.yml

---
- [Frontend](https://nr-spar-27.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2027-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2027-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): drop pins from allowlisted action org

---

frontend/src/views/CONSEP/TestingActivities/MoistureContent/index.tsx
frontend/src/views/CONSEP/TestingActivities/PurityContent/constants.ts
frontend/src/views/CONSEP/TestingActivities/PurityContent/index.tsx
frontend/src/views/CONSEP/TestingActivities/PurityContent/styles.scss
oracle-api/src/main/java/ca/bc/gov/oracleapi/endpoint/consep/MoistureContentConesEndpoint.java

Closes #1897
- complete and accept purity testing
---
- [Frontend](https://nr-spar-46.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2046-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2046-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: compete and accept the test

---

frontend/src/views/Seedlot/SeedlotDetails/index.tsx

---
- [Frontend](https://nr-spar-12.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2062-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2062-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(frontend): #2053 fix edit form button

---

frontend/src/views/CONSEP/TestingActivities/ActivityResult/constants.tsx
frontend/src/views/CONSEP/TestingActivities/ActivityResult/index.tsx
frontend/src/views/CONSEP/TestingActivities/PurityContent/index.tsx

Closes #issue
---
- [Frontend](https://nr-spar-36.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2086-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2086-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

feat: calculate purity value

---

frontend/package-lock.json
frontend/package.json
frontend/src/aws-exports.ts
frontend/src/contexts/AuthProvider.tsx
frontend/src/types/FamUser.ts

Upgrade frontend packages: axios, aws-amplify and cypress
---
- [Frontend](https://nr-spar-49.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2099-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2099-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(frontend): #2049 Upgrade frontend packages (major version update)

---

frontend/package-lock.json
frontend/src/components/ReadOnlyInput/styles.scss
frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/SingleOwnerInfo/styles.scss
frontend/src/views/Seedlot/SeedlotReview/styles.scss

Closes #2063 
- Added new styling rules.
- Styling rules for read-only fields at the ownership step on seedlot registration
- Nothing :)
---
- [Frontend](https://nr-spar-3.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2103-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2103-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: 2063 update the style for read only input

---

frontend/package-lock.json

---
- [Frontend](https://nr-spar-17.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2117-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2117-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(deps): fix frontend deps local running error

---

frontend/src/views/CONSEP/TestingActivities/MoistureContent/index.tsx
frontend/src/views/CONSEP/TestingActivities/PurityContent/index.tsx
oracle-api/src/main/java/ca/bc/gov/oracleapi/dto/consep/MoistureContentConesDto.java
oracle-api/src/main/java/ca/bc/gov/oracleapi/service/consep/MoistureContentService.java
oracle-api/src/test/java/ca/bc/gov/oracleapi/endpoint/consep/MoistureContentConesEndpointTest.java

- fix for mc page variation
---
- [Frontend](https://nr-spar-34.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2134-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2134-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix: mc page variations

---

frontend/src/views/Seedlot/SeedlotDetails/index.tsx

Closes #2157
---
- [Frontend](https://nr-spar-8.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2158-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2158-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(frontend): #2157 fix edit/view seedlot form button in detail screen

---

oracle-api/src/main/java/ca/bc/gov/oracleapi/ConsepOracleQueryConstants.java
oracle-api/src/main/java/ca/bc/gov/oracleapi/dto/consep/ActivitySearchRequestDto.java
oracle-api/src/main/java/ca/bc/gov/oracleapi/entity/consep/ActivitySearchResultEntity.java
oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/consep/ActivitySearchRepository.java
oracle-api/src/main/java/ca/bc/gov/oracleapi/service/consep/ActivitySearchService.java
oracle-api/src/test/java/ca/bc/gov/oracleapi/endpoint/consep/ActivitySearchEndpointTest.java
oracle-api/src/test/java/ca/bc/gov/oracleapi/service/consep/ActivitySearchServiceTest.java

Closes #2090
---
- [Frontend](https://nr-spar-18.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2168-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2168-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)
---
- [Frontend](https://nr-spar-18.apps.silver.devops.gov.bc.ca/)
- …

fix(oracle-api): #2090 add filter for germ try id and genetic code class

---

frontend/package-lock.json
frontend/package.json

Closes #2160
---
- [Frontend](https://nr-spar-28.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2178-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2178-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

fix(deps): #2160 Upgrade axios version

---

renovate.json

Update renovate config to use v1 instead of main/unstable for generating PRs.  Some config cleanup too.
---
- [Frontend](https://nr-spar-35.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-2185-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-2185-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

chore(ci): Mend Renovate v1 config
